Issues
Ran into an insecurePlatformWarning
- https://github.com/conda/conda/issues/1204
Switched from Python 2 to 3